FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
  ca-certificates \
  git \
  unzip \
  curl
# Instalar Composer y php-cs-fixer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && composer global require friendsofphp/php-cs-fixer

ENV PATH="/root/.composer/vendor/bin:$PATH"
WORKDIR /app
