services:
  server:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    networks:
      - php-network
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    env_file:
      - .env
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    networks:
      - php-network
    volumes:
      - ./www:/var/www
  db:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - php-network
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - .env
    links:
    # Links the PHPMyAdmin service to the MySQL database service
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=db
      # - PMA_ARBITRARY=1
      # Use MySQL root password for PHPMyAdmin
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - php-network

networks:
  php-network:
    driver: bridge

volumes:
  dbdata: